services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: ["poetry", "run", "python", "dashboard/app.py"]
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
