services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    command: ["poetry", "run", "python", "-m", "src.main"]  # Default command to run the scraper
    environment:
      - PYTHONUNBUFFERED=1  # Optional: Set environment variables if needed
